// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import './api/api_key.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: web_apiKey,
    appId: '1:178441102506:web:79368a60c74e89dcf31cd3',
    messagingSenderId: '178441102506',
    projectId: 'flutter-firebase-auth-36082',
    authDomain: 'flutter-firebase-auth-36082.firebaseapp.com',
    storageBucket: 'flutter-firebase-auth-36082.appspot.com',
    measurementId: 'G-60XHDDY4B9',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: android_apiKey,
    appId: '1:178441102506:android:342fdb5e921d58fff31cd3',
    messagingSenderId: '178441102506',
    projectId: 'flutter-firebase-auth-36082',
    storageBucket: 'flutter-firebase-auth-36082.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: ios_apiKey,
    appId: '1:178441102506:ios:0214289cc9a9ee90f31cd3',
    messagingSenderId: '178441102506',
    projectId: 'flutter-firebase-auth-36082',
    storageBucket: 'flutter-firebase-auth-36082.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: macOS_apiKey,
    appId: '1:178441102506:ios:4074b496c6e4c7eaf31cd3',
    messagingSenderId: '178441102506',
    projectId: 'flutter-firebase-auth-36082',
    storageBucket: 'flutter-firebase-auth-36082.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseAuth.RunnerTests',
  );
}
